name: FirelessEnchants
version: '${project.version}'
main: com.bobwazheer.plugins.firelessenchants.FirelessEnchants
api-version: 1.18
authors: [ BobWazHeer ]
website: twitch.tv/bobwazheer
commands:
  flameglow:
    description: Adds glow enchant to your tool
    usage: /<command>
